
#PRE-REQUISITO
namesecret: "connectionapic" #SECRET CONFIGURADO EN OPENSHIFT PREVIAMENTE

#EN APIC
nameorg: "demo-org" #CLIENT+INT
#Crear catalogo
space: "demo-space"


##PROJECT (CANVAS)
namecanvas: "org-int-dest"
namespace: "demo-ns"
namedashboardace: "demo-db"

##MQ - los nombres no puede tener caracteres

nameqm: "demoqm"
namems: "demoms" 
namequeue: "demoq"
namechannel: "democh"


##ACE
nameintegrationruntime: "country-b-02"
urlbar: "https://db-01-quickstart-3-dash.demo-banreservas:3443/v1/directories/CountryAPIproject.generated?2cfaa42a-f747-4d98-8be8-37a111c56f6c"
nameconfigurationmq: "democonfigmq"

##APIC
nameapi: "country-b-01"
nameproduct: "demo-product"


#DT
secretmqconnection: "accounts.yaml-test" #SECRET CONFIGURADO EN OPENSHIFT PREVIAMENTE
nameusermq: "demoapp"


