nameir: "test"
nameapi: "test"
nameproduct: "test"
urlbar: "https://db-01-quickstart-3-dash.demo-banreservas:3443/v1/directories/CountryAPIproject.generated?2cfaa42a-f747-4d98-8be8-37a111c56f6c"
namecanvas: ""
namespace: "test01"
namesecret: "test"
nameorg: "test"
urlmng: ""
api_key: ""
trusted_cert: ""
space: "test"
nameqm: "qmtest"