apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: {{ .Values.nameapi }}
  namespace: {{ .Values.namespace }}
spec:
  definition:
    integrationRuntime:
      name: {{ .Values.nameir }}
  share:
    apim:
      credentialsSecret: {{ .Values.namesecret }}
      providerOrg: {{ .Values.nameorg }}