apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: {{ .Values.nameapi }}
  namespace: {{ .Values.namespace }}
  labels:
    assembly.integration.ibm.com/{{ .Values.namespace }}.{{ .Values.namecanvas }}: 'true'
spec:
  definition:
    integrationRuntime:
      name: {{ .Values.nameir }}
  share:
    apim:
      credentialsSecret: {{ .Values.namesecret }}
      providerOrg: {{ .Values.nameorg }}