apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: {{ .Values.nameintegrationruntime }}
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
    assembly.integration.ibm.com/{{ .Values.namespace }}.{{ .Values.namecanvas }}: 'true'
#    {{ .Values.namecanvas }}.{{ .Values.namespace }}: 'true'
  namespace: {{ .Values.namespace }}
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProductionFREE
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 300m
              memory: 368Mi
          name: runtime
  logFormat: basic
  defaultNetworkPolicy:
    enabled: true
  replicas: 1
  version: '12.0.12-r12'
  barURL:
    - >-
      https://demo-db-dash.demo-ns:3443/v1/directories/CountryAPIproject.generated?92a946c2-6468-49bc-9369-a9475fecb6c2
  configurations:
    - {{ .Values.nameconfigurationmq }}
  forceFlowsHTTPS:
    enabled: true
