apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: {{ .Values.nameir }}
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  namespace: {{ .Values.namespace }}
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProductionFREE
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 300m
              memory: 368Mi
          name: runtime
  logFormat: basic
  defaultNetworkPolicy:
    enabled: true
  replicas: 1
  version: '12.0'
    - >-
      https://db-01-quickstart-3-dash.demo-banreservas:3443/v1/directories/CountryAPIproject.generated?2cfaa42a-f747-4d98-8be8-37a111c56f6c
  configurations: []
  forceFlowsHTTPS:
    enabled: true