apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: {{ .Values.nameir }}
  namespace: {{ .Values.namespace }}
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProductionFREE
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 300m
              memory: 368Mi
          name: runtime
  logFormat: basic
  defaultNetworkPolicy:
    enabled: true
  replicas: 1
  version: '12.0'
  barURL:
    - >-
      https://db-banbif-dash.app-banbif:3443/v1/directories/ExampleValidateJSON.regenerated?b617b73a-c52e-4924-a2b8-f3054d7ada8b
  configurations: []
  forceFlowsHTTPS:
    enabled: true