apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namesecret }}
  namespace: {{ .Values.namespace }}
  labels:
    assembly.integration.ibm.com/{{ .Values.namespace }}.{{ .Values.namecanvas }}: 'true'
type: Opaque
stringData:
  base_url: {{ .Values.urlmng }}
  grant_type: api_key
  api_key: {{ .Values.api_key }}
  trusted_cert: |-
    -----BEGIN CERTIFICATE-----
    MIIC9jCCAd6gAwIBAgIQA8HME22yl+WqEPji8TYOUDANBgkqhkiG9w0BAQsFADAV
    MRMwEQYDVQQDEwppbmdyZXNzLWNhMB4XDTI0MTAyMzAwMTEwMloXDTM0MTAyMTAw
    MTEwMlowFTETMBEGA1UEAxMKaW5ncmVzcy1jYTCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAKGa6Zi4EqH7QXf+6BYS6Kst3ZjgMmyX6Li4Vpj1hBZuvwhu
    DVqZW294rX8TDabJIfvq5uojxO2Wl4YHgkH4nUVebMgFWil0Tld2mPvCIlSZ3S5T
    wjIOGa5acQ30r2bpYwMgaYJYv9WNn+lRAO2f/BjSmJEgHpt7isnaN0ATm5lzSl/M
    iYaszLbsF2OSRuEMzh55yID61Zs6lZ6MxyGpNwPqoqk+swFD2Ukws/Paa6V0Dksa
    VLgWgz5Ww3Fyqo4aj8NlDZHfJkk/RxGdlfOu8noCFhgSufDcOcEvbijGkvOga4yd
    gfSufdmJVX1BkS32/+vbKGOcxwEMbbcp6kFYkwMCAwEAAaNCMEAwDgYDVR0PAQH/
    BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCNL78oVNUs3JF4QvRDg
    bdmtkYXzMA0GCSqGSIb3DQEBCwUAA4IBAQAeT8JLgIjx4M58/UoMGv0/Rxc0TgnD
    563lY5VEqmV5WiRynvKQxjlTjNhPSHoBT7LTcWcY2Aol8eTflYaRsGIlyGOw20lw
    o6bPmuPa8RkE8R6Tj+FRBXVAyCAJcG0B4aXvYuMciL4RtFCD02LB+gCp0abwH8mR
    1yWaHc3OcscpekmjDbhjLgv0Z4CXmVgR1WIOr8b1PYAgKUezEEv3api51q7xixy5
    7lxeea2989W+BR6GB55A/rkrJCyROMM1XpXvIBde/FrOqCy54hVdZKgdvtWrxK1L
    GGi339EZnqiDXVRBa9+VjOOEiviCvrNWiRq2hCTiTndf8FeGBx4Bfsr6
    -----END CERTIFICATE-----