apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namesecret }}
  namespace: {{ .Values.namespace }}
  labels:
    assembly.integration.ibm.com/{{ .Values.namespace }}.{{ .Values.namecanvas }}: 'true'
type: Opaque
stringData:
  base_url: {{ .Values.urlmng }}
  grant_type: api_key
  api_key: {{ .Values.api_key }}
  trusted_cert: |
    {{ .Values.trusted_cert }}