kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.namesecret }}
  namespace: {{ .Values.namespace }}
  labels:
    assembly.integration.ibm.com/{{ .Values.namespace }}.{{ .Values.namecanvas }}: 'true'
data:
  base_url: {{ .Values.urlmng }}
  username: {{ .Values.usermng }}
  password: {{ .Values.passmng }}
  client_id: {{ .Values.clientid }}
  client_secret: {{ .Values.clientsecret }}
  disable_trust: dHJ1ZQ==
  realm: YWRtaW4vZGVmYXVsdC1pZHAtMQ==
type: Opaque